name: new_html_editor_example
description: "Demonstrates how to use the new_html_editor plugin."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  new_html_editor:
    path: ../

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  equatable: ^2.0.7
  riverpod_annotation: ^2.6.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
