name: new_html_editor
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2
  video_player: ^2.9.5
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.4
  webview_flutter_platform_interface: ^2.10.0
  webview_flutter_wkwebview: ^3.18.5
  youtube_player_flutter: ^9.1.1
  youtube_player_iframe: ^5.2.1
  equatable: ^2.0.7
  chewie: ^1.11.0
  flutter_riverpod: ^2.6.1
  file_picker: ^10.0.0
  http: ^1.3.0
  path: ^1.9.1
  pointer_interceptor: ^0.10.1+2
  uuid: ^4.5.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
 
  plugin:
    platforms:
      android:
        package: com.newhtmleditor.new_html_editor
        pluginClass: NewHtmlEditorPlugin
      ios:
        pluginClass: NewHtmlEditorPlugin
      web:
        pluginClass: NewHtmlEditorWeb
        fileName: new_html_editor_web.dart

  assets:
      - packages/new_html_editor/assets/camera_roll_icon.png
      - packages/new_html_editor/assets/h1_dark.png
      - packages/new_html_editor/assets/h2_dark.png
      - packages/new_html_editor/assets/edit_table.png
      - packages/new_html_editor/assets/insert_table.png
      - packages/new_html_editor/assets/delete_column.png
      - packages/new_html_editor/assets/delete_row.png
      - packages/new_html_editor/assets/delete_table.png
      - packages/new_html_editor/assets/insert_column_left.png
      - packages/new_html_editor/assets/insert_row_above.png
      - packages/new_html_editor/assets/insert_row_below.png
      - packages/new_html_editor/assets/insert_column_right.png
      - packages/new_html_editor/assets/scripts/quill_2.0.0_4_min.js
      - packages/new_html_editor/assets/scripts/custom_quill.js